AssistantWebMySql/Controllers/ConsoleController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using AssistantWebMySql.DAL;
using AssistantWebMySql.Interfaces;
using AssistantWebMySql.Models;
using AssistantWebMySql.Models.DbSets;

namespace AssistantWebMySql.Controllers
{
    public class ConsoleController : Controller
    {
        private readonly IConsoleRepository _consoleRepository;

        public ConsoleController()
        {
            _consoleRepository = new ConsoleRepository(new AssistantContext());
        }

        // GET: Console/Index
        public ActionResult Index()
        {
            return User.Identity.IsAuthenticated ?
                (ActionResult)View(_consoleRepository.GetAllUsers()) : RedirectToAction("Login", "Account");
        }

        // POST: Console/Create
        [System.Web.Mvc.HttpPost]
        public ActionResult Create(RegisteredUser newUser)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

            _consoleRepository.AddNewUser(newUser);

            return RedirectToAction("Index");
        }

        // POST: Console/Edit
        [System.Web.Mvc.HttpPost]
        public ActionResult Edit(int? id, DateTime? newLicenseDate)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

            if (newLicenseDate == null || id == null)
                return View("Error");

            _consoleRepository.UpdateLicense(id.Value, newLicenseDate.Value);

            return RedirectToAction("Index");
        }

        // POST: Console/Delete
        [System.Web.Mvc.HttpPost]
        public ActionResult Delete(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

            if (id == null)
                return View("Error");

            _consoleRepository.Delete(id.Value);

            return RedirectToAction("Index");
        }

        // POST: Console/AuthRequest
        [System.Web.Mvc.HttpPost]
        public HttpStatusCodeResult AuthRequest([FromBody] RegisteredUser parameters)
        {
            return _consoleRepository.GetUser(parameters.Name, parameters.KeyHash) == null ? 
                new HttpStatusCodeResult(404) : new HttpStatusCodeResult(200);
        }

        // POST: Console/RegisterRequest
        [System.Web.Mvc.HttpPost]
        public HttpStatusCodeResult RegisterRequest([FromBody] RegisteredUser parameters)
        {
            if (parameters == null)
                return new HttpStatusCodeResult(404);

            return !_consoleRepository.AddNewUser(parameters) ?
                new HttpStatusCodeResult(404) : new HttpStatusCodeResult(200);
        }
    }
}

AssistantWebMySql/Views/Console/Index.cshtml
@using AssistantWebMySql.Models.DbSets
@model List<AssistantWebMySql.Models.DbSets.RegisteredUser>
@{
    ViewBag.Title = "Управление пользователями";
}
@section Scripts {
    @Scripts.Render("~/scripts/validate.min.js")
}
<h2 class="pt-5 text-center">@ViewBag.Title</h2>

@Html.Partial("_AddNewUser", new RegisteredUser())

<div class="container-fluid">
    <h4 class="pt-5">Список пользователей:</h4>
    <div class="row">
        <table style="table-layout: fixed;word-wrap: break-word;" class="table table-striped table-responsive-sm table-responsive-md table-responsive-lg">
            <thead class="bg-dark">
                <tr>
                    <th style="width: 4%" class="text-light text-center">@Html.LabelFor(model => model[0].Id)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].Name)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].Surname)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].Address)</th>
                    <th style="width: 25%" class="text-light text-center">@Html.LabelFor(model => model[0].KeyHash)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].MacAdress)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].RegistrationDate)</th>
                    <th class="text-light text-center">@Html.LabelFor(model => model[0].LicenseFinishDate)</th>
                    <th style="width: 10%" class="text-light text-center"><label>Продлить до</label></th>
                    <th class="text-light text-center"><label>Обновить</label></th>
                    <th class="text-light text-center"><label>Удалить</label></th>
                </tr>
            </thead>
            @foreach (RegisteredUser registeredUser in Model)
            {
                <tr class="border-bottom">
                    @using (Html.BeginForm("Edit", "Console", new { id = registeredUser.Id }, FormMethod.Post))
                    {
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.Id)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.Name)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.Surname)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.Address)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.KeyHash)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.MacAdress)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.RegistrationDate)</td>
                        <td class="text-center mt-2">@Html.DisplayTextFor(registeredUserItem => registeredUser.LicenseFinishDate)</td>
                        <td class="text-center mt-2"><input class="form-control", type="date" name="newLicenseDate"/></td>
                        <td class="text-center mt-2">
                            <button type="submit" class="btn btn-success">Обновить</button>
                        </td>
                    }
                    @using (Html.BeginForm("Delete", "Console", new { id = registeredUser.Id }, FormMethod.Post))
                    {
                        <td class="text-center mt-2">
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
</div>

AssistantWebMySql/Views/Console/_AddNewUser.cshtml
@model AssistantWebMySql.Models.DbSets.RegisteredUser

<div class="container">
    <h4 class="pt-5">Добавить нового пользователя:</h4>
    @using (Html.BeginForm("Create", "Console", FormMethod.Post))
    {
        <div class="row justify-content-around bg-light border-top pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.Name)</span>
                </div>
                @Html.TextBoxFor(model => model.Name, new { @class = "col form-control" })
            </div>
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.Surname)</span>
                </div>
                @Html.TextBoxFor(model => model.Surname, new { @class = "col form-control" })
            </div>
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.Company)</span>
                </div>
                @Html.TextBoxFor(model => model.Company, new { @class = "col form-control" })
            </div>
        </div>

        <div class="row justify-content-around bg-light border-bottom pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">Эл. почта</span>
                </div>
                @Html.TextBoxFor(model => model.Address, new { @class = "col form-control" })
            </div>
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.MacAdress)</span>
                </div>
                @Html.TextBoxFor(model => model.Address, new { @class = "col form-control" })
            </div>
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.LicenseFinishDate)</span>
                </div>
                @Html.TextBoxFor(model => model.LicenseFinishDate, new { @class = "col form-control", type = "date" })
            </div>
        </div>

        <button type="submit" class="col btn btn-success form-control mt-2" id="btnLogin">Добавить</button>
    }
</div>