AssistantWebMySql/Models/DbSets/Update.cs
using System.ComponentModel.DataAnnotations;

namespace AssistantWebMySql.Models.DbSets
{
    public class Update
    {
        [Key]
        [Display(Name = "№, пп")]
        public int Id { get; set; }

        [Display(Name = "Версия")]
        public string Version { get; set; }

        [Display(Name = "Русский")]
        public string RussianDescription { get; set; }

        [Display(Name = "Английский")]
        public string EnglishDescription { get; set; }

        [Display(Name = "Немецкий")]
        public string DeutschDescription { get; set; }

        [Display(Name = "Китайский")]
        public string ChineseDescription { get; set; }

        [Display(Name = "Ссылка на скачивание")]
        public string DownLoadLink { get; set; }
    }

    public class UpdateJson
    {
        public int Language { get; set; }

        public string Version { get; set; }

        public string Description { get; set; }

        public string DownLoadLink { get; set; }
    }
}

AssistantWebMySql/Controllers/UpdateController.cs
using System.Web.Http;
using System.Web.Mvc;
using AssistantWebMySql.DAL;
using AssistantWebMySql.Interfaces;
using AssistantWebMySql.Models;
using AssistantWebMySql.Models.DbSets;

namespace AssistantWebMySql.Controllers
{
    public class UpdateController : Controller
    {
        private readonly IUpdateRepository _updateRepository;

        public UpdateController()
        {
            _updateRepository = new UpdateRepository(new AssistantContext());
        }

        // GET: Update/Index
        public ActionResult Index()
        {
            return User.Identity.IsAuthenticated ?
                (ActionResult)View(_updateRepository.GetAllUpdates()) : RedirectToAction("Login", "Account");
        }

        // POST: Update/Add
        [System.Web.Mvc.HttpPost]
        public ActionResult Add(Update updateData)
        {
            if (updateData == null)
                return View("Error");

            if (!User.Identity.IsAuthenticated)
                return View("Error");

            _updateRepository.AddNew(updateData);

            return RedirectToAction("Index");
        }

        // POST: Update/Delete/7
        [System.Web.Mvc.HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return View("Error");

            if (!User.Identity.IsAuthenticated)
                return View("Error");

            _updateRepository.Delete(id.Value);

            return RedirectToAction("Index");
        }

        // GET: Update/Download/7
        public ActionResult Download(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            if (!User.Identity.IsAuthenticated)
                return View("Error");

            string downloadLink = _updateRepository.GetDownloadLink(id.Value);

            return string.IsNullOrEmpty(downloadLink) ?
                (ActionResult)View("Error") : Redirect(downloadLink);
        }

        // GET: Update/CheckVersion
        public JsonResult CheckVersion([FromBody] UpdateJson checkVersion)
        {
            if (checkVersion == null)
                return null;

            UpdateJson updateJson = _updateRepository.GetUpdateJson(checkVersion);

            return updateJson != null ? 
                Json(updateJson,JsonRequestBehavior.AllowGet) : null;
        }
    }
}

AssistantWebMySql/Views/Update/Index.cshtml
@using AssistantWebMySql.Models.DbSets
@model IEnumerable<Update>
@{
    ViewBag.Title = "Список версий";
}

<h2 class="pt-5 text-center">@ViewBag.Title</h2>

@Html.Partial("_AddUpdate", new Update { Version = "1.0.0.x", DownLoadLink = "http://" })

<div class="container-fluid">
    <h4 class="pt-5">Доступные версии:</h4>
    <table class="table">
        <tr>
            <th class="text-center">@Html.DisplayNameFor(model => model.Version)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.RussianDescription)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.EnglishDescription)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.DeutschDescription)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.ChineseDescription)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.DownLoadLink)</th>
            <th class="text-center">Удалить</th>
        </tr>
        @foreach (Update item in Model)
        {
            <tr>
                <td class="text-center">@Html.DisplayTextFor(modelItem => item.Version)</td>
                <td class="text-center">@Html.DisplayTextFor(modelItem => item.RussianDescription)</td>
                <td class="text-center">@Html.DisplayTextFor(modelItem => item.EnglishDescription)</td>
                <td class="text-center">@Html.DisplayTextFor(modelItem => item.DeutschDescription)</td>
                <td class="text-center">@Html.DisplayTextFor(modelItem => item.ChineseDescription)</td>
                <td class="text-center">@Html.ActionLink("Скачать", "Download", "Update", new {id = item.Id}, new {@class = "btn btn-info"})</td>
                @using (Html.BeginForm("Delete", "Update", new { id = item.Id }, FormMethod.Post))
                {
                    <td class="text-center"><button type="submit" class="btn btn-danger">Удалить</button></td>
                }
            </tr>
        }
    </table>
</div>

AssistantWebMySql/Views/Update/_AddUpdate.cshtml
@model AssistantWebMySql.Models.DbSets.Update


<div class="container">
    <h4 class="pt-5">Добавить новую версию:</h4>
    @using (Html.BeginForm("Add", "Update", FormMethod.Post))
    {
        <div class="row justify-content-around bg-light border-top pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.Version)</span>
                </div>
                @Html.TextBoxFor(model => model.Version, new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around bg-light pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.RussianDescription)</span>
                </div>
                @Html.TextArea("RussianDescription", new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around bg-light pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="col input-group-text">@Html.DisplayNameFor(model => model.EnglishDescription)</span>
                </div>
                @Html.TextArea("EnglishDescription", new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around bg-light pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.DeutschDescription)</span>
                </div>
                @Html.TextArea("DeutschDescription", new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around bg-light pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="input-group-text">@Html.DisplayNameFor(model => model.ChineseDescription)</span>
                </div>
                @Html.TextArea("ChineseDescription", new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around bg-light border-bottom pb-2">
            <div class="col input-group mt-2">
                <div class="input-group-prepend">
                    <span class="col input-group-text">@Html.DisplayNameFor(model => model.DownLoadLink)</span>
                </div>
                @Html.TextBoxFor(model => model.DownLoadLink, new { @class = "col form-control" })
            </div>
        </div>
        <div class="row justify-content-around pb-2">
            <div class="col input-group mt-2">
                <input type="submit" class="col btn btn-success" value="Добавить новую версию"/>
            </div>
        </div>
    }
</div>